modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/NinjaPhenix/ExpandedStorage/issues/"
license = "All Rights Reserved"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[36.1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
