modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/NinjaPhenix/ExpandedStorage/issues/"
license = "All Rights Reserved"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[37.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"
